from pathlib import Path

path = Path('Src/Win/CutMask.cpp')
text = path.read_text(encoding='utf-8')

old_geometry = '''    const float outlineThickness = 1.f;\n    // The target frame must have exactly the same outer bounds as the 7px\n    // square created by the horizontal/vertical cross intersection. Keeping\n    // an 11px frame here made the black target visibly overhang the cross by\n    // two pixels on every side during an active drag. The 1px black border is\n    // drawn inward, so the 5x5 center remains transparent for color inspection.\n    const float crossL = centerPxX - 3.f * scale;\n    const float crossT = centerPxY - 3.f * scale;\n    const float crossR = centerPxX + 4.f * scale;\n    const float crossB = centerPxY + 4.f * scale;\n    // Draw the 1px black target border OUTSIDE the 7x7 cross-intersection\n    // square. The transparent observation area therefore remains exactly\n    // crossL..crossR / crossT..crossB, while the complete outer target is 9x9\n    // at 100% DPI. No border pixel is allowed to consume the sampled center.\n    const float frameL = crossL - 1.f * scale;\n    const float frameT = crossT - 1.f * scale;\n    const float frameR = crossR + 1.f * scale;\n    const float frameB = crossB + 1.f * scale;\n'''

new_geometry = '''    const float outlineThickness = 1.f;\n    // Snipaste-style dual-contrast target. The sampled center stays exactly\n    // the same 7x7 square made by the cross intersection. Around that, draw a\n    // 1px white ring (9x9 outer bounds), then a 1px black ring (11x11 outer\n    // bounds). This keeps the locator visible on both dark and light content\n    // without covering any pixel inside the 7x7 observation area.\n    const float crossL = centerPxX - 3.f * scale;\n    const float crossT = centerPxY - 3.f * scale;\n    const float crossR = centerPxX + 4.f * scale;\n    const float crossB = centerPxY + 4.f * scale;\n    const float whiteL = crossL - 1.f * scale;\n    const float whiteT = crossT - 1.f * scale;\n    const float whiteR = crossR + 1.f * scale;\n    const float whiteB = crossB + 1.f * scale;\n    const float frameL = whiteL - 1.f * scale;\n    const float frameT = whiteT - 1.f * scale;\n    const float frameR = whiteR + 1.f * scale;\n    const float frameB = whiteB + 1.f * scale;\n'''

if old_geometry not in text:
    raise SystemExit('Expected magnifier geometry block not found')
text = text.replace(old_geometry, new_geometry, 1)

old_border = '''    // Four equal filled bars guarantee the top/bottom/left/right border has\n    // identical thickness. Do not fill the center.\n    ctx->FillRectangle(D2D1::RectF(frameL, frameT, frameR, frameT + outlineThickness), brushCenterBorder.Get());\n    ctx->FillRectangle(D2D1::RectF(frameL, frameB - outlineThickness, frameR, frameB), brushCenterBorder.Get());\n    ctx->FillRectangle(D2D1::RectF(frameL, frameT + outlineThickness, frameL + outlineThickness, frameB - outlineThickness), brushCenterBorder.Get());\n    ctx->FillRectangle(D2D1::RectF(frameR - outlineThickness, frameT + outlineThickness, frameR, frameB - outlineThickness), brushCenterBorder.Get());\n'''

new_border = '''    // Two hard-edged one-pixel rings: black outside, white inside. The 7x7\n    // center itself is never painted, so it remains a true transparent/sample\n    // window. Four filled bars avoid DrawRectangle half-pixel rasterization.\n    ctx->FillRectangle(D2D1::RectF(frameL, frameT, frameR, frameT + outlineThickness), brushCenterBorder.Get());\n    ctx->FillRectangle(D2D1::RectF(frameL, frameB - outlineThickness, frameR, frameB), brushCenterBorder.Get());\n    ctx->FillRectangle(D2D1::RectF(frameL, frameT + outlineThickness, frameL + outlineThickness, frameB - outlineThickness), brushCenterBorder.Get());\n    ctx->FillRectangle(D2D1::RectF(frameR - outlineThickness, frameT + outlineThickness, frameR, frameB - outlineThickness), brushCenterBorder.Get());\n\n    ctx->FillRectangle(D2D1::RectF(whiteL, whiteT, whiteR, whiteT + outlineThickness), brushText.Get());\n    ctx->FillRectangle(D2D1::RectF(whiteL, whiteB - outlineThickness, whiteR, whiteB), brushText.Get());\n    ctx->FillRectangle(D2D1::RectF(whiteL, whiteT + outlineThickness, whiteL + outlineThickness, whiteB - outlineThickness), brushText.Get());\n    ctx->FillRectangle(D2D1::RectF(whiteR - outlineThickness, whiteT + outlineThickness, whiteR, whiteB - outlineThickness), brushText.Get());\n'''

if old_border not in text:
    raise SystemExit('Expected magnifier border block not found')
text = text.replace(old_border, new_border, 1)
path.write_text(text, encoding='utf-8')
